### ISSUE TITLE
periodic short gap of not audio in Android

### ISSUE THREAD

**Issue by zxpectre** [zombience/audio_analyzer#2] opened 2016-07-23 21:24 UTC
## Periodic short gap of not audio in Android:

There is a repetitive short gap of no audio tested using no baked audio (realtime mic or input capture), this happends on Android and I believe is happening in Windows as well but on PC this gap seems to be much shorter, almost inaudible. 

I believe is a lapse of time during mic stop-start again capturing on audio clip. Is there any workaround to fix this? @zombience  your code is clean and perfect! but I really need this gap to go away and I don't know where to start. Can you help me?

**Comment by zombience** [comment] 2016-07-23 22:00
Hi there, glad you're getting use out of the code!
I haven't been aware of a gap, but I've also never tested this code on
Android or iOS.  I've only ever used this on Mac and pc, since I've been
doing live visuals for events with this.

Unfortunately I can't test anything out currently, I'm on a 3 month
sabbatical with no computer at hand.

In my code I was conscientious to stop the Mic and restart in the same
frame. It is conceivable that I'd you're running at 30 for, that could be a
long enough gap to be audible, altho theoretically it shouldn't happen.
Also, I wrote this code without intending to ever hear the audio, only to
use it as input. The scenario I've used this in is dj sets and live music
where the audio feed is already being sent into the environment, and
unity3d is just another endpoint for audio rather than a throughput.

If I were to sit down and troubleshoot this, I would attempt to use the
AudioSettings.dspTime to retrigger a new action at a specific tic. The dsp
occurs on a different thread, so you can initiate events with far more
precision than main thread events which are locked to framerate than if you
hook into dspTime.

Unfortunately I cannot test anything out for you, but hopefully that's
enough to get you started.

This may not help you now, but I can get back to this in October when. I
return.

One other thing you may investigate is the library of Keijiro Takahashi who
has a far more advanced code base for reactive audio libraries for
unity3d.  I assume you've already implemented my code and would rather
continue with that for less effort, but if you can afford the extra time,
his library is far more developed than mine.

Best luck!
Sorry I can't be of more help.

Jason

---

Not sure why it's important to note that this was sent from a phone... But
it was.

**Comment by zombience** [comment] 2016-07-24 12:50
Hi there, glad you're getting use out of the code!
I haven't been aware of a gap, but I've also never tested this code on
Android or iOS.  I've only ever used this on Mac and pc, since I've been
doing live visuals for events with this.

Unfortunately I can't test anything out currently, I'm on a 3 month
sabbatical with no computer at hand.

In my code I was conscientious to stop th. Mic and restart in the same
frame. It is conceivable that I'd you're running at 30 for, that could be a
long enough gap to be audible, altho theoretically it shouldn't happen.

If I were to sit down and troubleshoot this, I would attempt to use the
AudioSettings.dspTime to retrigger a new action at a specific tic. The dsp
occurs on a different thread, so you can initiate events with far more
precision if you hook into dspTime.

Unfortunately I cannot test anything out for you, but hopefully that's
enough to get you started.

This may not help you now, but I can get back to this in October when. I
return.
Best luck!
Sorry I can't be of more help.

Jason
________
Not sure why it's important to note that this was sent from a phone... But
it was.

On Jul 23, 2016 23:24, "zxpectre" <notifications@github.com> wrote:

Periodic short gap of not audio in Android:

There is a repetitive short gap of no audio tested using no baked audio
(realtime mic or input capture), this happends on Android and I believe is
happening in Windows as well but on PC this gap seems to be much shorter,
almost inaudible.

I believe is a lapse of time during mic stop-start again capturing on audio
clip. Is there any workaround to fix this? @zombience
<https://github.com/zombience> your code is clean and perfect! but I really
need this gap to go away and I don't know where to start. Can you help me?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zombience/audio_analyzer/issues/2>, or mute the thread

**Comment by zxpectre** [comment] 2016-07-24 18:36
Thanks for your useful reply @zombience ! , because of a deadline I had to try your suggestion ( [Reaktion](http://keijiro.github.io/projects/reaktion.html) ) **BUT** I liked your code, is lightweight and does the job,  I'm following your repository in case you, I or someone fix that minor Android issue. 
Enjoy your sabbatical time! :) 

Thanks!
ZX

**Comment by Darth-Carrotpie** [comment] 2016-11-13 17:33
I've witnessed same issue. In my case, the gap sounds more of random noise crackle, when loop is being restarted. Tested this with debug, so it's definitely happening then. IMHO, it's caused by phase not being restarted properly, and, thus, being overlaped by newly started recording. But that's just a theory... Anyways, in my actual case this will not matter, the issue needs some kind of fix in the long term tho...
Edit: my case is Windows.

**Comment by zombience** [comment] 2016-11-13 17:39
I will address this issue within the next few weeks.

When I originally developed this, I had no intention of listening to the
play-through audio, it was only put in place as a debug feature. I am aware
of the click, but it wasn't important to my usage.

It seems that there are people who would find that a useful feature, so I
will look into it soon.

Cheers

Jason Araujo

---

Not sure why it's important to note that this was sent from a phone... But
it was.

**Comment by samavan** [comment] 2017-07-06 00:22
Also having the same gap every 4-5s on Windows!
Only occurs for direct input. 
The baked sounds works a charm!

**Comment by zombience** [comment] 2017-07-06 01:26
Hey there, 
sorry to hear you're having issues with this. 
I have been really busy with other projects and so have unfortunately let this go for a while. I do want to get back into this. 
When I do, I have a major update that I've been working on in another branch that will take care of this audio gap, and a host of other issues. 
The bad news is that it will be a major API-breaking update, so projects using this current package will have to make changes to implement the new package. 

I'll try to keep the API as close as possible so that most changes will be easy, but I will err on the side of making a better package, and make breaking changes if it means that the audio analyzer will work better and be easier to use. 

In the meantime, I have no intention to fix this issue on this branch, because it will be solved with major updates. 

Sorry about that, best of luck. Glad you are getting use out of this repo.

**Comment by samavan** [comment] 2017-07-21 07:46
is reorg_refractor is the new  branch?

**Comment by zombience** [comment] 2017-07-22 00:30
it's the one that i'm currently working in. you can check it out if you like, but do so at your own risk. it is under development and constantly being refactored. nothing is guaranteed to work there, and i will definitely be changing things as i go. 
but the core does currently work, so go ahead and check it out if you like

**Comment by zombience** [comment] 2017-09-01 20:48
Closing this issue as it will not be fixed in this version. The updated version is hopefully coming soon, as I now have some free time to work on this.

**Closed as completed by zombience** 2017-09-01 20:48 UTC

**Comment by zombience** [comment] 2017-09-07 22:23
Hey @zxpectre, I've created a new beta branch for people to use if you're still interested in this project.
I've worked on a lot of new improvements and have created a new "beta" branch. 

If you are still interested in the project, I'd really appreciate some testing and feedback. There are some pretty great improvements all across the board: updated inspectors, updated math, and a few extra fx. 

Thanks for your interest, and I hope you get some good use out of it. Let me know if you have any feedback!

Again, that's the "beta" branch
